version: '3.5'

services :
    python:
      container_name: python_37
      build:
        context: .
        dockerfile: dockerfiles/Dockerfile.api
      environment:
      - PROJECT_ID=ml-project-24
      - ENVIRONMENT=production
      ports:
        - 8080:8080
      volumes:
        - ./../../:/home/4aibd-annuel-project
      stdin_open: true
      tty: true

networks:
  default:
    driver: bridge
    
    
