from .db import db

class Mail(db.Document):
    idMail = db.StringField(required=True, unique=True)
    threadId = db.StringField(required=True)
    historyId = db.ListField(db.StringField(), required=True)
    labelIds = db.ListField(db.StringField(), required=True)
    snippet = db.StringField(required=True)
    payloadPartId = db.ListField(db.StringField(), required=True)
    payloadMimeType = db.ListField(db.StringField(), required=True)
    deliveredTo = db.ListField(db.StringField(), required=True)
    received = db.ListField(db.StringField(), required=True)
    xGoogleSmtpSource = db.ListField(db.StringField(), required=True)
    xReceived = db.ListField(db.StringField(), required=True)
    arcMessageSignature = db.ListField(db.StringField(), required=True)
    arcAuthenticationResults = db.ListField(db.StringField(), required=True)
    returnPath = db.ListField(db.StringField(), required=True)
    receivedSPF = db.ListField(db.StringField(), required=True)
    authenticationResults = db.ListField(db.StringField(), required=True)
    dKimsSignature = db.ListField(db.StringField(), required=True)
    headersMessageId = db.ListField(db.StringField(), required=True)
    mimeVersion = db.ListField(db.StringField(), required=True)
    From = db.ListField(db.StringField(), required=True)
    to = db.ListField(db.StringField(), required=True)
    subject = db.ListField(db.StringField(), required=True)
    date = db.ListField(db.StringField(), required=True)
    headersListId = db.ListField(db.StringField(), required=True)
    headersListUnsubscribe = db.ListField(db.StringField(), required=True)
    precedence = db.ListField(db.StringField(), required=True)
    xCsaComplaints = db.ListField(db.StringField(), required=True)
    xMjMid = db.ListField(db.StringField(), required=True)
    xMjMimeMessageStructure = db.ListField(db.StringField(), required=True)
    feedbackId = db.ListField(db.StringField(), required=True)
    contentType = db.ListField(db.StringField(), required=True)
    size = db.StringField(required=True)
    body = db.ListField(db.StringField(), required=True)
    mimeType =db.ListField(db.StringField(), required=True)