version: '3.5'

services :
    python:
      container_name: datalab_python
      build: python
      volumes:
         - ./../../a_collect_gmail/:/home/a_collect_gmail/
         - ./../../b_transform_gmail/:/home/b_transform_gmail/
         - ./../../default/:/home/default/
         - ./../../resources/:/home/resources/
      stdin_open: true
      tty: true

    rundeck :
      container_name: datalab_rundeck
      build: rundeck
      ports :
         - "4440:4440"
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      stdin_open: true

    notebook:
      container_name: datalab_anaconda3
      build: anaconda3
      ports:
        - "8888:8888"
      volumes:
        - ./anaconda3/notebooks/:/home/4aibd-s1-project-ml
      stdin_open: true
      tty: true  

    