FROM python:3.8-slim

VOLUME ./ika_streamer/:/app/

WORKDIR /app

ENV MONGO_URI=ika_db:27017

COPY . /app/

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r /app/requirements.txt \
    && rm -rf /root/.cache/pip

EXPOSE 8000

CMD uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --workers 16