FROM python:3.8-slim


COPY . /app/
WORKDIR /app

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r /ika_streamer/requirements.txt 

ENV MONGO_URI=ika_db:27017

EXPOSE 8000

CMD uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --workers 16