version: '3.5'

services :
    python:
      container_name: prod_python
      build: python
      volumes:
         - ./../../a_collect_gmail/:/home/a_collect_gmail/
         - ./../../b_transform_gmail/:/home/b_transform_gmail/
         - ./../../c_usecase_gmail/:/home/c_usecase_gmail/
         - ./../../default/:/home/default/
         - ./../../resources/:/home/resources/
      ports :
         - "8080:8080"
      command : bash -c "./run_neomail.sh"
      stdin_open: true
      tty: true

