apiVersion: v1
kind: Service
metadata:
  name: ika-streamer
spec:
  type: LoadBalancer
  loadBalancerIP: 35.232.119.203
  selector:
    app: ika-streamer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
