apiVersion: v1
kind: Service
metadata:
  name: ika-web
spec:
  loadBalancerIP: 35.232.119.203
  type: LoadBalancer
  selector:
    app: ika-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
