apiVersion: apps/v1
kind: Deployment
metadata:
  name: ika-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ika-web
  template:
    metadata:
      labels:
        app: ika-web
    spec:
      containers:
        - name: ika-web
          image: gcr.io/formation-mac-298810/ika-web:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"