apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  loadBalancerIP: 35.232.119.203
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
