apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.production.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: smtpd
  name: smtpd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smtpd
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.production.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: smtpd
    spec:
      containers:
        - image: smtpd
          name: smtpd
          ports:
            - containerPort: 1025
          resources: {}
      restartPolicy: Always
status: {}
